
[functions.oracle-journal]
enabled = true
verify_jwt = true
import_map = "./functions/oracle-journal/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/oracle-journal/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/oracle-journal/*.html" ]

[functions.oracle-weekly]
enabled = true
verify_jwt = true
import_map = "./functions/oracle-weekly/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/oracle-weekly/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/oracle-weekly/*.html" ]
